#!/bin/bash
#  echo "Holberton School" > \\\*\\\\'\'\"Holberton\ School\"\\\''\\\\\*\$\\\*\\\*\\\*\\\*\\\*\:\)
  echo "Holberton School" > '\*\\'\''"Holberton School"\'\''\\*$\?\*\*\*\*\*:)'
#  \*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
