#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”
sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
print %s "server {
	listen		80 default_server;
	listen		[::]:80 default_server;
	root		/etc/nginx/html;
	index		index.html index.htm;

	location	/redirect_me {
		return 301 http://cuberule.com/;
	}

}
" > /etc/nginx/sites-available/default

service nginx restart
