#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”
INDEX_COPY="Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "$INDEX_COPY" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
