#!/usr/bin/env bash
# Installs and configures HAproxy-2.0
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt -y install haproxy

FILE="/etc/haproxy/haproxy.cfg"

server_1="3.235.21.36"
server_2=" 3.83.35.54 "

FRONTEND="\nfrontend LBfrontend\n\tbind *:80\n\tdefault_backend servers\n"
BACKEND="\nbackend servers\n\tbalance roundrobin\n\tserver server_1 $server_1\n\tserver server_2 $server_2\n"

echo -e "$FRONTEND" | sudo tee -a "$FILE" 
echo -e "$BACKEND" | sudo tee -a "$FILE"

sudo service haproxy restart
