#!/usr/bin/env bash
# displays information about the holbertonschool file

filename="holbertonschool"

if [ -e $filename ]
then
    echo "holbertonschool file exists"
    if [ -s $filename ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ -f $filename ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
